import Header from "@/components/ui/header";
import "@sap-ui/common-css/dist/sap-container-type.css";
import "@sap-ui/common-css/dist/sap-content-paddings.css";
import '@ui5/webcomponents-react/styles.css'
import { ThemeProvider } from "@ui5/webcomponents-react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider >
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Header />
          <main className="sap-container-type-inline-size">
            <div>{children}</div>
          </main>
        </body>
      </ThemeProvider>
    </html>
  );
}
